
# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      #enabled: false
      server:
        git:
           uri: https://github.com/ramoncalabozo/SuperComputacion.git
           # uri: https://github.com/avadop/spring_config_curso_babel.git
           # uri: https://github.com/migueldoctor/SpringCloudConfig-GitRepository

  # profiles:
   # active: dev
